-- Inserimento categorie CPV
INSERT INTO categoria_cpv (id, codice, descrizione) VALUES
(3, 'CPV7e1b54', 'Servizi di consulenza commerciale e di gestione'),
(4, 'CPVe6074a', 'Servizi di piantagione e manutenzione di zone verdi'),
(5, 'CPVba84a9', 'Lavori di manutenzione stradale'),
(6, 'CPVa3361e', 'Impianti meccanici'),
(7, 'CPV46ca7d', 'Servizi di gestione di impianti sportivi'),
(8, 'CPVf01df4', 'Microscopi'),
(9, 'CPVce45d7', 'Lavori di costruzione di condotte idriche e fognarie'),
(10, 'CPV38a0ca', 'Lavori di ristrutturazione'),
(11, 'CPVa79f25', 'Misuratori di pressione'),
(12, 'CPV2e6add', 'Lavori stradali'),
(13, 'CPV872f3e', 'Servizi di organismi di riscossione'),
(14, 'CPVdb8057', 'Servizi di biblioteche'),
(15, 'CPV385772', 'Servizi di ristorazione scolastica'),
(16, 'CPVc3598a', 'Servizi cimiteriali'),
(17, 'CPV788062', 'Lavori edili'),
(18, 'CPV8f097f', 'Lavori di difesa dalle piene'),
(19, 'CPV6ea672', 'Servizi di musei'),
(20, 'CPV0a51ce', 'Servizi di tesoreria'),
(21, 'CPV0b6bee', 'Servizi di trattamento e smaltimento di rifiuti urbani e domestici non pericolosi'),
(22, 'CPVe37164', 'Distributori automatici'),
(23, 'CPV331ae4', 'Servizi di consulenza e informazione giuridica'),
(24, 'CPVbe8940', 'Attrezzature varie per giardinaggio'),
(25, 'CPV89cc96', 'Attrezzature ferroviarie'),
(26, 'CPVf79f21', 'Sistema di videosorveglianza'),
(27, 'CPV60acd2', 'Servizi di assistenza sociale'),
(28, 'CPVaed1d0', 'Toner per stampanti laser/apparecchi fax'),
(29, 'CPVfaa5db', 'Servizi di trasporto pubblico terrestre'),
(30, 'CPV2c1fc7', 'Servizi assicurativi'),
(31, 'CPV5d6022', 'Servizi alberghieri'),
(32, 'CPV864529', 'Servizi di assistenza sociale per bambini e giovani'),
(33, 'CPV791079', 'Vari servizi di ingegneria'),
(34, 'CPV106533', 'Servizi di riparazione e manutenzione di contatori d\'acqua'),
(35, 'CPVade767', 'Servizi di pulizia e disinfestazione'),
(36, 'CPV2a067f', 'Sistemi diagnostici'),
(37, 'CPV056ed8', 'Servizi di assunzione'),
(38, 'CPV22aa0f', 'Reattivi chimici'),
(39, 'CPVadfa81', 'Servizi per rete informatica'),
(40, 'CPV0d1df5', 'Riparazione, manutenzione e servizi affini connessi alle strade ed altre attrezzature')
ON CONFLICT (codice) DO NOTHING;

-- Reset sequenza
SELECT setval('categoria_cpv_id_seq', (SELECT MAX(id) FROM categoria_cpv));
